picos:
  population: '"Aged"[Mesh] OR "Aged, 80 and over"[Mesh] OR "Elderly"[tiab]'
  intervention: '"Dental Implants"[Mesh] OR "Dental Implant*"[tiab]'
  comparison: '"Denture, Partial, Removable"[Mesh] OR "Denture*"[tiab] OR "Partial
    denture*"[tiab]'
  outcome: '"Occlusion"[Mesh] OR "Mastication"[Mesh] OR "Function"[Mesh] OR "Success
    rate"[tiab]'
  study_design: '"Comparative Study"[pt] OR "Review"[pt] OR "Randomized Controlled
    Trial"[pt]'
