picos:
  population: '"Child"[Mesh] OR "Adolescent*"[tiab] OR "Adult"[tiab] OR "Pediatric*"[tiab]'
  intervention: '"Orthodontics"[Mesh] OR "Orthodontic*"[tiab] OR "Brace*"[tiab]'
  comparison: '"Adult"[tiab] OR "Adolescent*"[tiab] OR "Child"[Mesh]'
  outcome: '"Prognosis"[Mesh] OR "Treatment outcome"[tiab] OR "Success rate"[tiab]
    OR "Predictor*"[tiab]'
  study_design: '"Comparative Study"[pt] OR "Cohort Studies"[Mesh] OR "Meta-analysis"[pt]'
  email: chemahc94@pusan.ac.kr
  api_key: ''
  enable_scihub_fallback: true
